### ISSUE TITLE
Meet fatal error when I try to install the Release version that I get ffrom github through App Installer or Powershell

### ISSUE THREAD

**Issue by Looong01** [microsoft/vscode-explorer-command#13]
Error 0x800B0100: The app package must be digitally signed for signature verification.
![image](https://user-images.githubusercontent.com/69568351/194246103-30d94552-dce7-4ae3-9b33-9af3e441c75c.png)
![image](https://user-images.githubusercontent.com/69568351/194246052-b7d84179-3822-49c3-bb75-09e0a22a4b40.png)

**Comment by deepak1556** [comment]
The releases in this repo are not meant for end user consumption since they are not signed. Appx packages are signed as part of the VSCode installation https://github.com/microsoft/vscode/pull/151186
