### ISSUE TITLE
Bad certification

### ISSUE THREAD

**Issue by DanRotaru** [microsoft/vscode-explorer-command#4]
I can't install because your app don't have valid certification
![image](https://user-images.githubusercontent.com/7759507/171146149-ec89725e-9f1c-4685-8c69-56fdebf7d2e1.png)

Этот пакет приложения не подписан достоверным сертификатом. Обратитесь к системному администратору или разработчику приложения, чтобы получить новый сертификат или пакет приложения с достоверными сертификатами. Корневой сертификат и все непосредственные сертификаты подписи в пакете приложения должны быть достоверными (0x800B010A)

Or in english

This app package is not signed with a trusted certificate. Contact your system administrator or app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all direct signing certificates in the application package must be valid (0x800B010A)

**Comment by deepak1556** [comment]
As mentioned in https://github.com/microsoft/vscode-explorer-command#vscode-explorer-command this repository does not create signed packages.
