### ISSUE TITLE
Windows cannot install package because it must be installed with an external location

### ISSUE THREAD

**Issue by xBiei** [microsoft/vscode-explorer-command#5]
I managed to sign the package myself but I got this weird error and it doesn't even make sense cuz the dll file is included in the appx file.
![image](https://user-images.githubusercontent.com/65196493/171609686-3a64755a-719b-4077-9896-b5a06394875f.png)

I even tried it with -AllowUnsigned arg, but still the same error.

**Comment by Nirmal4G** [comment]
This is a spare package meaning that it will need a parent program install location and a manifest to be present in that location. Then you'll need to refer the install location of the parent application (_VS Code in our case_) and register the sparse package with that location (_e.g.: `%ProgramFiles%\Microsoft VS Code\`_).

**Comment by Nirmal4G** [comment]
[Sparse Package samples](https://aka.ms/sparsepkgsample)

**Comment by deepak1556** [comment]
Yup as mentioned above package should be installed alongside the VSCode installed directory since resources in the manifest refer to it.

**Comment by StarNumber12046** [comment]
so I have to copy everything to %ProgramFiles%\Microsoft VS Code\?
